version: '3.8'

services:
  app:
    container_name: spotify_feature
    build: ./docker
    ports:
      - 9000:9000
    privileged: true
    volumes:
      - ./app:/app:cached
    tty: true
    stdin_open: true
    command: npm run dev